config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root "users#index"

  get '/admin/email'

  get '/page/:page' => 'users#page'

  resources :password_resets
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  get '/category/:id' => 'categories#show', as: 'category'
  get '/category/:id/page/:page' => 'categories#page', as: 'category_page'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create', as: 'user_session'
  get '/logout' => 'sessions#destroy', as: 'logout'

  scope path: "/users", controller: :users do
    post '/' => 'users#create'
    get 'new' => 'users#new', as: 'new_user'
    get 'forgotpassword' => :forgot_password_form, as: 'forgot_password'
  end

  get '/:username' => "users#show", as: 'user'
  post '/:username' => "users#update"
  get '/:username/edit' => "users#edit", as: 'edit_user'
  get '/:username/delete' => 'users#request_destroy', as: 'delete_user'
  post '/:username/delete' => 'users#destroy', as: 'confirm_delete_user'

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_and_belongs_to_many :categories

  #self.per_page = 16

  # add password_confirmation
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }, if: ->(record) { record.new_record? || record.password.present? }
  validates :password_confirmation, presence: true, if: ->(record) { record.new_record? || record.password.present? }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, length: { maximum: 400 }
  validates :tagline, length: { maximum: 30 }


  validates :email, uniqueness: true

  mount_uploader :avatar, AvatarUploader

  def full_name
    first_name + " " + last_name
  end

  def category_id
    self.category.id
  end

  def category
    self.categories.first
  end

  def linkedin_username
    matches = self.linkedin.match(regex_pattern)
    matches[4]
  end

  def facebook_username
    matches = self.facebook.match(regex_pattern)
    matches[4]
  end

  def twitter_username
    matches = self.twitter.match(regex_pattern)
    matches[4]
  end

  def instagram_username
    matches = self.instagram.match(regex_pattern)
    matches[4]
  end

  def github_username
    matches = self.github.match(regex_pattern)
    matches[4]
  end

  def tumblr_username
    matches = self.tumblr.match(regex_pattern)
    matches[4]
  end

  def dribbble_username
    matches = self.dribbble.match(regex_pattern)
    matches[4]
  end

  def pinterest_username
    matches = self.pinterest.match(regex_pattern)
    matches[4]
  end

  private

  def regex_pattern
    # This method returns a new Regexp object using the given pattern.
    pattern = "^(https?:\/\/)?(www.)?(facebook.com\/|linkedin.com\/|twitter.com\/|instagram.com\/|github.com\/|dribbble.com\/|pinterest.com\/)?(.*)"
    Regexp.new(pattern, Regexp::IGNORECASE)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:edit, :request_destroy, :destroy]
  before_action :set_random_seed, only: [:index, :page]

  def set_random_seed
    session[:seed] ||= rand
    session[:seed] = rand if !params[:page]
  end

  def index
    @categories = Category.all

    User.connection.execute("select setseed(#{session[:seed]})")

    @users = User.joins(:categories).select("users.id, users.username, users.first_name, users.last_name, users.avatar, categories.name AS category_name").
    order("RANDOM()").page(1)

    @user = User.new
  end

  def page
    User.connection.execute("select setseed(#{session[:seed]})")

    @users = User.joins(:categories).select("users.id, users.username, users.first_name, users.last_name, users.avatar, categories.name AS category_name").
    order("RANDOM()").page(params[:page])

    render partial: 'partials/polaroid'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to edit_user_path(@user.username)
    else
      @categories = Category.all
      render :new
    end
  end

  def edit_params
    params.require(:user).permit(:email, :username, {category_ids: []},
    :first_name, :last_name, :avatar, :bio, :website, :company, :company_site,
    :facebook, :dribbble, :twitter, :linkedin, :github, :pinterest, :instagram,
    :tagline, :tumblr, :googleplus)
  end

  def user_params
    params.require(:user).permit(:email, :username, :password, {category_ids: []},
    :password_confirmation, :first_name, :last_name, :avatar)
  end

  def admin_email
    if current_user.admin?
      render :admin_email
    else
      flash.notice = "Forbidden: requires administrator access"
      render :error_message
    end
  end

  def new
    @categories = Category.all
  end

  def login
  end

  def forgot_password_form
  end

  def assign_new_password
    @user = User.find_by_email(params[:user][:email.downcase])
  end


  def edit
    if current_user.username == params[:username]
      @categories = Category.all
      @user = User.find_by_username(params[:username])
    else
      redirect_to root_path
    end
  end

  def show
    if @user = User.find_by_username(params[:username])
      render :show
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find_by_username(params[:username])
    if @user.update_attributes(edit_params)
      @message = "Profile updated successfully!"
      redirect_to user_path(@user.username)
    else
      @categories = Category.all
      render :edit
    end
  end

  def request_destroy
    @username = params[:username]
  end

  def destroy
    user = User.find_by_username(params[:username])
    user.destroy
    redirect_to root_path, notice: "Your account has been deleted."
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'partials/navbar.html' %>
<div class="container block">
  <h1>Edit Your Profile</h1>
  <hr>
  <div class="row">
    <%= form_for :user, url: "/#{@user.username}", html: { class: "form-horizontal", role: "form"} do |f| %>

      <div class="col-md-3">
        <div class="text-center">
          <div class="profile_pic">
            <%= image_tag @user.avatar.url(:thumb), class: "avatar", alt: "avatar" %>
          </div>
          <h4>Change profile photo</h4>
          <%= f.file_field :avatar, class: 'form-control' %>
          <h4 class="mobile_only">iOS users, take photos in landscape mode!</h4>
        </div>
      </div>

      <div class="col-md-9 personal-info">
        <% if @user && @user.errors.count > 0 %>
          <div class="form-errors">
            <p>Please review and correct the following errors:</p>
            <% @user.errors.each do |key, value| %>
              <li><%= "#{key} #{value}" %></li>
            <% end %>
          </div>
        <% end %>
          <h3>Personal Info</h3>

          <div class="form-group">
            <%= f.label :first_name, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :last_name, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :username, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :username, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :tagline, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :tagline, class: "form-control" %>
            </div>
          </div>

          <h3>Select Speciality</h3>
          <h4>Select a primary speciality:</h4>
          <div class="form-group">
             <label class="col-xs-2 col-md-3 control-label">Category:</label>
             <div class="col-xs-offset-2 col-md-8">
               <%= f.select :category_ids, options_from_collection_for_select(@categories, :id, :name, @user.category_id), {}, name: "user[category_ids][]" %>
             </div>
          </div>
          <!-- <div class="form-group">
            <h4>Select any other skills:</h4>
            <div class="row">
              <div class="col-sm-4 col-sm-offset-3 category_block">
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Web & Software
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Graphic Design
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Architecture & Interior Design
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Photography
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Music/Film/Art
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Fashion
                </label>
              </div>


              <div class="col-sm-3 category_block">
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Writing
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Venture Capital
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Community Connector
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Non-Profit
                </label>
                <label class="">
                  <input type="checkbox" name="inlineRadioOptions" value=""> Sales & Marketing
                </label>
              </div>
            </div>
          </div> -->

          <h3>Add Your Portfolio</h3>
          <h4>These fields are optional</h4>
          <h4>Please only enter your social media username for each (not URL)</h4>

          <div class="form-group">
            <%= f.label :company, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :company, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :company_site, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :company_site, class: "form-control" %>
            </div>
          </div>
         <div class="form-group">
           <%= f.label :twitter, class: "col-md-3 control-label" %>
           <div class="col-md-8">
             <%= f.text_field :twitter, class: "form-control" %>
           </div>
         </div>
          <div class="form-group">
            <%= f.label :facebook, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :facebook, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :github, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :github, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :dribbble, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :dribbble, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :pinterest, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :pinterest, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :linkedin, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :linkedin, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :instagram, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :instagram, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :website, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :website, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :bio, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_area :bio, class: "form-control", rows: "8" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="save col-md-3 col-md-push-7 control-label">
            <%= f.submit "Save your changes" %>
          </div>
      </div>
    <% end %>
    <form action="../<%= @user.username %>/delete" class="container">
      <div class="row">
        <div class="form-group col-md-3 col-md-push-7 text-center">
          <input type="button" class="delete" value="Delete Profile">
        </div>
      </div>
    </form>
  </div>
</div>
<hr>

app/views/users/index.html.erb
<%= render partial: '/partials/navbar' %>
<div class="container sort_by">
  <div class="row">
    <a href= "/">
      <div class="category_button col-sm-2 all <%= "highlighted" if !@highlighted %>">
        <small class="sorter">All</small>
      </div>
    </a>
    <% @categories.each do |cat| %>
      <% (@highlighted == cat.short_category_name)? add_on = " highlighted" : add_on = "" %>
      <a href= "/category/<%= cat.id %>">
        <div class="col-sm-2 <%= cat.short_category_name + add_on %>">
          <small class="sorter"><%= cat.name %></small>
        </div>
      </a>
    <% end %>
  </div>
</div>

<div class="container sort_by_mobile_mode">
  <div class="row">
    <%= select_tag("category", options_from_collection_for_select(@categories, "id", "name", params[:id]), :id => 'mobile_select', :include_blank => 'View Faces By Category', :onchange => 'window.location.href = "/category/" + this.value') %>
<!--, :onchange => 'window.location.href = "category/" + this.getAttribute("value")' -->
  </div>
</div>

<div class="container" id="polaroid_container">

  <div id="polaroids-row" class="row">
      <%= render partial: 'partials/polaroid' %>
  </div>

</div>
<div class="bubble" id="upwards">^</div>

app/views/users/new.html.erb
<%= render 'partials/navbar.html' %>

<div class="container block">
  <h1>Add your profile</h1>
  <hr>
  <div class="row">
    <%= form_for :user, url: "/users", html: { class: "form-horizontal", role: "form"} do |f| %>

      <div class="col-md-3">
        <div class="text-center">
          <%= image_tag 'profile_pic.jpg', class: "avatar img-thumbnail", alt: "avatar" %>
          <h4>Add profile photo</h4>
          <%= f.file_field :avatar, class: 'form-control' %>
          <h4 class="mobile_only">iOS users, take photos in landscape mode!</h4>
        </div>
      </div>

      <div class="col-md-9 personal-info">
        <% if @user && @user.errors %>
          <div class="form-errors">
            <p>Please review and correct the following errors:</p>
            <% @user.errors.each do |key, value| %>
              <li><%= "#{key} #{value}" %></li>
            <% end %>
          </div>
        <% end %>
          <h3>Personal Info</h3>

          <div class="form-group">
            <%= f.label :first_name, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :first_name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :last_name, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :last_name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :email, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.password_field :password, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :username, class: "col-md-3 control-label" %>
            <div class="col-md-8">
              <%= f.text_field :username, class: "form-control" %>
            </div>
            <br>
            <h4>(Note, usernames are only used for linking to your profile.)</h4>
          </div>

          <h3>Select Speciality</h3>
          <h4>Select a primary speciality:</h4>
          <div class="form-group">
             <label class="col-xs-2 col-md-3 control-label">Category:</label>
             <div class="col-xs-offset-2 col-md-8">
               <%= f.select :category_ids, options_from_collection_for_select(@categories, :id, :name), {}, name: "user[category_ids][]" %>
             </div>
          </div>

          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="text-center">
              <%= f.submit "Add Your Profile" %>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>
<hr>

app/views/users/request_destroy.html.erb
Are you sure you want to delete this profile?

<%= link_to "Yes", confirm_delete_user_path(@username), method: :post %>
<%= link_to "No", edit_user_path(@username) %>

app/views/users/show.html.erb
<%= render partial: '/partials/navbar' %>
<div class="container block">
  <div class="row">
    <div class="col-sm-6 text-center">
      <div class="profile_pic" >
        <% if @user.avatar.url(:thumb) != nil %>
          <%= image_tag @user.avatar.url(:thumb) %>
        <% else %>
          <%= image_tag 'profile_pic.jpg' %>
        <% end %>
      </div>
      <% if current_user && (current_user.username == @user.username) %>
        <form action="../<%= @user.username %>/edit">
            <input type="submit" value="Edit your Profile" class="cool">
        </form>
      <% end %>
    </div>
    <div class="col-sm-6">
      <h1 class="<%= Category.find(@user.category_id).short_category_name %> rokkitt"><%= @user.full_name %></h1>
      <h2 class="rokkitt"><%= Category.find(@user.category_id).name.titleize %></h2>
      <% if @user.tagline && @user.tagline != ""  %>
        <p class="tagline">"<%= @user.tagline %>"</p>
      <% end %>
      <hr>
      <% if @user.bio && @user.bio != "" %>
        <h2 class="rokkitt">Bio:</h2>
          <p><%= @user.bio %></p>
      <% end %>
      <table class="site_table">
        <% if @user.website && @user.website != ""%>
          <tr><td><strong>Personal Site:</strong></td> <td><a href='<%= @user.website %>'><%= @user.website %></a></td></tr>
        <% end %>
        <% if @user.company && @user.company != "" %>
          <tr><td><strong>Company Site:</strong></td> <td><a href='<%= @user.company_site %>'><%= @user.company %></a></td></tr>
        <% end %>
      </table>
      <% if (@user.company && @user.website != "") || (@user.website && @user.website != "") %>
        <hr>
      <% end %>
      <ul>
        <% if @user.facebook != "" && @user.facebook != nil %>
          <a href="http://facebook.com/<%= @user.facebook_username %>"><li>Facebook</li></a>
        <% end %>
        <% if @user.twitter != "" && @user.twitter != nil %>
          <a href="http://twitter.com/<%= @user.twitter_username %>"><li>Twitter</li></a>
        <% end %>
        <% if @user.instagram != "" && @user.instagram != nil %>
          <a href="http://instagram.com/<%= @user.instagram_username %>"><li>Instagram</li></a>
        <% end %>
        <% if @user.linkedin != "" && @user.linkedin != nil %>
          <a href="http://linkedin.com/<%= @user.linkedin_username %>"><li>LinkedIn</li></a>
        <% end %>
        <% if @user.github != "" && @user.github != nil %>
          <a href="http://github.com/<%= @user.github_username %>"><li>Github</li></a>
        <% end %>
        <% if @user.tumblr != "" && @user.tumblr != nil %>
          <a href="http://tumblr.com/<%= @user.tumblr %>"><li>Tumblr</li></a>
        <% end %>
        <% if @user.dribbble != "" && @user.dribbble != nil %>
          <a href="http://dribbble.com/<%= @user.dribbble_username %>"><li>Dribbble</li></a>
        <% end %>
        <% if @user.pinterest != "" && @user.pinterest != nil %>
          <a href="http://pinterest.com/<%= @user.pinterest_username %>"><li>Pinterest</li></a>
        <% end %>
      </ul>
    </div>
  </div>
</div>